### ISSUE TITLE
Possible bug in applyGate

### ISSUE THREAD

**Issue by HumpyBlumpy** [zpcian/MPSQuantumJump#1]
Hi,
Thanks for posting this!
It seems to me that there is a bug in the applyGate function.
I think there should be a call to  psi.position(gatelist.front().i1()); at the very beginning before the while loop.
Without it I was getting a b-1 > l_orth_lim error.

**Comment by zpcian** [comment]
Sorry for the late reply!
I've add the line psi.position(gatelist.front().i1()); before the while loop.
Thank you for pointing it out!
